pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }

        stage('Deliver') {
            agent {
                docker {
                    image 'wushie/my_pyinstaller_image:8'
                    args '--entrypoint=""'
                }
            }
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }

        stage('Manual Approval') {
            agent any
            steps {
                script {
                    // Ask for manual approval before deploying
                    input(message: 'Lanjutkan ke tahap Deploy?', ok: 'Proceed', submitterParameter: 'APPROVE_DEPLOY')
                }
            }
        }

        stage('Deploy') {
            agent any
            when {
                // Only run this stage if the approval input is "Proceed"
                expression { return env.APPROVE_DEPLOY == 'Proceed' }
            }
            steps {
                script {
                    // Ambil kunci pribadi dari kredensial Jenkins
                    withCredentials([file(credentialsId: 'wushsecret', variable: 'SSH_KEY')]) {
                        // Salin artifact ke instans EC2
                        sh 'scp -i $SSH_KEY dist/add2vals ubuntu@54.169.230.31:/home/ubuntu/'
                    }
                }
                // Sleep for 1 minute after successful deployment
                sleep(time: 1, unit: 'MINUTES')
            }
        }
    }
}
