pipeline {
    agent any

    environment {
        VOLUME = "${pwd()}/sources:/src"
        IMAGE = 'cdrx/pyinstaller-linux:python2'
    }

    stages {
        stage('Preparation') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    image 'cdrx/pyinstaller-linux:python2'
                }
            }
            steps {
                sh "docker run --rm -v ${env.VOLUME} ${env.IMAGE} 'pyinstaller -F sources/add2vals.py'"
            }
            post {
                success {
                    archiveArtifacts "sources/dist/add2vals"
                }
            }
        }
    }
}
